# The basic colors
foreground              #24bd5c
background              #23262d
selection_foreground    #ffa96b
selection_background    #1b4e2a

# Cursor colors
cursor                  #24bd5c
cursor_text_color       #24bd5c

# URL underline color when hovering with mouse
url_color               #5494fc

# Kitty window border colors
active_border_color     #24bd5c
inactive_border_color   #24bd5c
bell_border_color       #24bd5c

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #24bd5c
active_tab_background   #23262d
inactive_tab_foreground #b5ccba
inactive_tab_background #23262d
tab_bar_background      #23262d

# Colors for marks (marked text in the terminal)
mark1_foreground #23262d
mark1_background #24bd5c
mark2_foreground #23262d
mark2_background #ffa96b
mark3_foreground #23262d
mark3_background #5494fc

# The 16 terminal colors

# black
color0 #23262d
color8 #23262d

# red
color1 #ff6b6b
color9 #ff6b6b

# green
color2  #24bd5c
color10 #24bd5c

# yellow
color3  #f9c859
color11 #f9c859

# blue
color4  #5494fc
color12 #5494fc

# magenta
color5  #9d72ff
color13 #9d72ff

# cyan
color6  #36d6c3
color14 #36d6c3

# white
color7  #e0e3e4
color15 #e0e3e4
