# Retro
# Theme create by: https://github.com/puszkarek
# Update by(sort by time):

# Thank you!

code_syntax_highlight = "gruvbox"

# border
file_panel_border = "#24bd5c"
sidebar_border = "#24bd5c"
footer_border = "#24bd5c"

# border active
file_panel_border_active = "#ffa96b"
sidebar_border_active = "#ffa96b"
footer_border_active = "#ffa96b"
modal_border_active = "#ffa96b"

# background (bg)
full_screen_bg = "#23262d"
file_panel_bg = "#23262d"
sidebar_bg = "#23262d"
footer_bg = "#23262d"
modal_bg = "#050505"

# foreground (fg)
full_screen_fg = "#24bd5c"
file_panel_fg = "#24bd5c"
sidebar_fg = "#24bd5c"
footer_fg = "#24bd5c"
modal_fg = "#24bd5c"

# special color
cursor = "#24bd5c"
correct = "#9d72ff"
error = "#ff6b6b"
hint = "#5494fc"
cancel = "#ff6b6b"
gradient_color = ["#24bd5c", "#24bd5c"]

# file panel special items
file_panel_top_directory_icon = "#24bd5c"
file_panel_top_path = "#24bd5c"
file_panel_item_selected_fg = "#ffa96b"
file_panel_item_selected_bg = "#23262d"

# sidebar special items
sidebar_title = "#24bd5c"
sidebar_item_selected_fg = "#ffa96b"
sidebar_item_selected_bg = "#23262d"
sidebar_divider = "#24bd5c"

# modal special items
modal_cancel_fg = "#23262d"
modal_cancel_bg = "#ff6b6b"

modal_confirm_fg = "#23262d"
modal_confirm_bg = "#24bd5c"

# help menu
help_menu_hotkey = "#24bd5c"
help_menu_title = "#24bd5c"
