[ui]
font_color = "#24bd5c"

main_foreground_color = "#24bd5c"
secondary_foreground_color = "#24bd5c"

main_background_color = "#23262d"
secondary_background_color = "#23262d"

[others]
selection_highlight_color = "#d0f9f4"
environment_variable_highlight_color = "#5494fc"

[methods]
GET = "#0f630c"
POST = "#49360b"
PUT = "#0b4949"
PATCH = "#0b2849"
DELETE = "#490b0b"
HEAD = "#0f630c"
OPTIONS = "#490b49"